# Generated by Django 3.2.9 on 2022-02-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebakerorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cost',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
